### ISSUE TITLE
some questions about the dimensionality

### ISSUE THREAD

**Issue by hit-joseph** [peter3125/sentence2vec#12]
thank you for your code!
I have read the source paper and your codes, just have some confuse about the embedding dimensionality. does the dimensionality of the word and sentence embedding should be the same ? in your code ,it is yes, but I think that the paper said it use pca and pca is used for dimensionality。 so in my opinion the dimensionality of sentence embedding  should be less than word , am I right?

**Comment by rock3125** [comment]
In Google's work, the sentence dimensionality is larger than the word embeddings (e.g. 300 vs. 512).  The algorithm here more or less "sums" the word vectors with weightings - so its dimensionality has to be the same for this algorithm.  From memory (it's been a while since I read the paper) - PCA is used to neutralize / offset some of the highest variant features in the summed vectors.
